#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/board;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#    jpa:
#      hibernate:
#        ddl-auto: create
#      properties:
#        hibernate:
##          show_sql: true
#          format_sql: true


spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2.console.enabled: true



#logging:
#  level:
#    org.hibernate.SQL: debug

